name: iOS Flutter Build (iOS)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          cache: true

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup

      - name: Install dependencies
        run: flutter pub get

      - name: Install iOS pods
        working-directory: ios
        run: pod install

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Upload iOS build artifact (for workflow artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/iphoneos

      # Create GitHub Release (only on push, not PRs)
      - name: Create Release
        if: github.event_name == 'push'
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Release v${{ github.run_number }}"
          body: "Automatic iOS release from CI workflow."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload iOS build to Release
      - name: Upload iOS build to Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          files: build/ios/iphoneos/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
