name: iOS Flutter Build (iOS)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          cache: true

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup

      - name: Install dependencies
        run: flutter pub get

      - name: Install iOS pods
        working-directory: ios
        run: pod install

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Upload iOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/iphoneos
